-- ====================================================================
-- SUPABASE FULL SCHEMA INITIALIZATION & RLS SETUP
-- ====================================================================
-- Target Database: Supabase PostgreSQL
-- Purpose: Creates the schema for the IB Physics Gravitation Space Repetition Ledger,
--          spanning student profiles, syllabus subtopics, the core curriculum question matrix,
--          and the spaced repetition master ledger.
--          Also configures Row-Level Security (RLS) to permit prototype evaluations.
-- ====================================================================

-- --------------------------------------------------------------------
-- Step 1: Initialize User Performance Profile Index
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
    current_estimated_band INT DEFAULT 2 CHECK (current_estimated_band BETWEEN 1 AND 7)
);

-- --------------------------------------------------------------------
-- Step 2: Initialize Syllabus Learning Ladder Dictionary
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS subtopics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL, -- e.g., 'TOPIC_6_1'
    title TEXT NOT NULL,
    syllabus_level TEXT NOT NULL CHECK (syllabus_level IN ('SL', 'HL'))
);

-- --------------------------------------------------------------------
-- Step 3: Create the Core Curriculum Question Matrix
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS question_bank (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subtopic_code TEXT REFERENCES subtopics(code) ON DELETE CASCADE NOT NULL,
    tier INT NOT NULL CHECK (tier BETWEEN 1 AND 3), -- 1: Intuition Anchor, 3: Handwritten Paper 2 Derivation
    question_text TEXT NOT NULL,
    hints JSONB DEFAULT '{}'::jsonb, -- Custom structural exponent guidance variables
    markscheme_criteria TEXT[] DEFAULT '{}'::text[] -- Step-by-step rigorous checking constraints
);

-- --------------------------------------------------------------------
-- Step 4: Establish the Long-Term Spaced Repetition Ledger
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS student_mastery_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    subtopic_id BIGINT REFERENCES subtopics(id) ON DELETE CASCADE NOT NULL,
    confidence_level INT NOT NULL CHECK (confidence_level BETWEEN 0 AND 2),
    rubric_score_achieved INT NOT NULL CHECK (rubric_score_achieved BETWEEN 0 AND 3),
    current_interval_days INT DEFAULT 0 NOT NULL,
    last_reviewed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    next_review_due TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT unique_user_subtopic UNIQUE (user_id, subtopic_id)
);

-- --------------------------------------------------------------------
-- Step 5: ROW-LEVEL SECURITY (RLS) SETUP & ACCESS BYPASS FOR PROTOTYPES
-- --------------------------------------------------------------------

-- Ensure Row-Level Security (RLS) is fully active on all tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE subtopics ENABLE ROW LEVEL SECURITY;
ALTER TABLE question_bank ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_mastery_ledger ENABLE ROW LEVEL SECURITY;

-- Drop prior policies if existing to avoid duplication errors
DROP POLICY IF EXISTS "Permit Anonymous Prototype Submissions" ON profiles;
DROP POLICY IF EXISTS "Permit Anonymous Prototype Submissions" ON subtopics;
DROP POLICY IF EXISTS "Permit Anonymous Prototype Submissions" ON question_bank;
DROP POLICY IF EXISTS "Permit Anonymous Prototype Submissions" ON student_mastery_ledger;

-- Create open public access bypass policies for prototype evaluation tracking runs
CREATE POLICY "Permit Anonymous Prototype Submissions" ON profiles FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Permit Anonymous Prototype Submissions" ON subtopics FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Permit Anonymous Prototype Submissions" ON question_bank FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Permit Anonymous Prototype Submissions" ON student_mastery_ledger FOR ALL TO anon USING (true) WITH CHECK (true);
